WIP on bringing in CUDA Toolkit 13.0.
This does not work because nvcc 13.0.8 is not compatible with glibc 2.42 yet:

  /usr/include/x86_64-linux-gnu/bits/mathcalls.h(206): error: exception
  specification is incompatible with that of previous function "rsqrt"
  (declared at line 629 of
  /usr/local/cuda-13.0/bin/..//include/crt/math_functions.h)

    extern double rsqrt (double __x) noexcept (true); extern double __rsqrt (double __x) noexcept (true);